import { Roboto_Condensed, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const robotoCondensed = Roboto_Condensed({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Landing Page",
  description: "Generated by David Pal  ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${robotoCondensed.variable} ${inter.variable} antialiased `}
        style={{
          fontFamily: "var(--font-body)",
          color: "var(--color-text-primary)",
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
